name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: Chaopy.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [windows]
        arch: [x64]
        qt_version: [5.15.2]
        qtarch: [win64_msvc2019_64]

    steps:
    - uses: actions/checkout@v4
    - name: Install MSVC compiler
      uses: ilammy/msvc-dev-cmd@v1
      with:
        # 14.1 is for vs2017, 14.2 is vs2019, following the upstream vcpkg build from Qv2ray-deps repo
        toolset: 14.2
        arch: ${{ matrix.arch }}       
    # Cache Qt
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: QtCache-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.qt_version }}

    # Install Qt
    - name: Installing Qt - ${{ matrix.arch }}
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}
        arch: ${{ matrix.qtarch }}
        mirror: "http://mirrors.ocf.berkeley.edu/qt/"
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    - name: Set Qt Version for MSBuild
      run: |
        setx QT_MSVC_DIR "C:\Qt\5.15.2\msvc2019_64"
        setx PATH "%QT_MSVC_DIR%\bin;%PATH%"
    - name: Generate Qt Configuration
      run: |
        echo "<Project><PropertyGroup><QtInstallDir>C:\Qt\5.15.2\msvc2019_64</QtInstallDir></PropertyGroup></Project>" > src/QtMsBuild/qt_vars.targets
        
    # Setup MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    # Install NSIS
    - name: Install NSIS
      uses: repolevedavaj/install-nsis@v1.0.1
      with:
        nsis-version: '3.10'

    # Build solution
    - name: Build the solution
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:OutDir=bin\Release\ /p:QtInstallDir=C:\Qt\5.15.2\msvc2019_64 ${{env.SOLUTION_FILE_PATH}}

    # Show binary files
    - name: Show binary files
      run: |
        dir /b bin\${{env.BUILD_CONFIGURATION}}
