name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: Chaopy.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [windows]
        arch: [x64]
        qt_version: [5.15.2]
        qtarch: [win64_msvc2019_64]

    steps:
    - uses: actions/checkout@v4

    # Cache Qt
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: QtCache-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.qt_version }}

    # Install Qt
    - name: Installing Qt - ${{ matrix.arch }}
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}
        arch: ${{ matrix.qtarch }}
        mirror: "http://mirrors.ocf.berkeley.edu/qt/"
        cached: ${{ steps.cache-qt.outputs.cache-hit }}

    # Setup MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    # Install NSIS
    - name: Install NSIS
      uses: repolevedavaj/install-nsis@v1.0.1
      with:
        nsis-version: '3.10'

    # Build solution
    - name: Build the solution
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:OutDir=bin\Release\ ${{env.SOLUTION_FILE_PATH}}

    # Show binary files
    - name: Show binary files
      run: |
        dir /b bin\${{env.BUILD_CONFIGURATION}}
