name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    # install qt
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: QtCache-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.qt_version }}
    - name: Installing Qt - ${{ matrix.arch }}
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}
        arch: ${{ matrix.qtarch }}
        mirror: "http://mirrors.ocf.berkeley.edu/qt/"
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
    # install msbuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    # install nsis
    - name: Install NISI
      uses: repolevedavaj/install-nsis@v1.0.1
      with:
        nsis-version: '3.10'
    # build solution
    - name: Build the solution
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
    # Show binary files
    - name: Show binary files
      working-directory: ${{env.GITHUB_WORKSPACE}}\bin\${{env.BUILD_CONFIGURATION}}
      run: |
        dir /b
    
    
    
        
