name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PROJECT_NAME: Chaopy
  SOLUTION_FILE_PATH: Chaopy.sln
  EXECUTABLE_FILE_PATH: Chaopy.exe
  BUILD_CONFIGURATION: Release
  QT_ARCH: msvc2019_64
  BUILD_VERSION: v1.0.0

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [windows]
        arch: [x64]
        qt_version: [5.15.2]
        qtarch: [win64_msvc2019_64]

    steps:
    - uses: actions/checkout@v4
    - name: Install MSVC compiler
      uses: ilammy/msvc-dev-cmd@v1
      with:
        # 14.1 is for vs2017, 14.2 is vs2019, following the upstream vcpkg build from Qv2ray-deps repo
        toolset: 14.2
        arch: ${{ matrix.arch }}       
    # Cache Qt
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: QtCache-${{ matrix.platform }}-${{ matrix.arch }}-${{ matrix.qt_version }}

    # Install Qt
    - name: Installing Qt - ${{ matrix.arch }}
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ matrix.qt_version }}
        arch: ${{ matrix.qtarch }}
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        dir: '${{ github.workspace }}'
      
    # Setup MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    # Build solution
    - name: Build the solution
      run: |
        msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:DebugSymbols=false /p:DebugType=None /p:QtInstallDir=${{github.workspace}}\Qt\${{matrix.qt_version}}\${{env.QT_ARCH}} ${{env.SOLUTION_FILE_PATH}}
        windeployqt ${{github.workspace}}\bin\${{env.BUILD_CONFIGURATION}}\${{env.EXECUTABLE_FILE_PATH}} --no-translations
# del ${{github.workspace}}\bin\${{env.BUILD_CONFIGURATION}}\*.pdb
        
    - name: Install NSIS
      run: |
        iwr -useb get.scoop.sh -outfile 'install.ps1'
        .\install.ps1 -RunAsAdmin
        scoop update
        scoop bucket add extras
        scoop install nsis
    - name: Print NSIS version
      run: makensis -VERSION
    - name: Print NSIS compile flags
      run: makensis -HDRINFO

    - name: Package with NSIS
      run: |
        makensis ${{github.workspace}}\setup\Chaopy_Setting.nsi

    - name: Upload Zip
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.PROJECT_NAME}}_${{matrix.platform}}_${{matrix.arch}}_${{env.BUILD_VERSION}}
        path: ${{github.workspace}}\bin\${{env.BUILD_CONFIGURATION}}\
    
    - name: Upload installer
      uses: actions/upload-artifact@v4
      with:
        path: ${{github.workspace}}\setup\${{env.PROJECT_NAME}}_${{matrix.platform}}_${{matrix.arch}}_${{env.BUILD_VERSION}}.exe
